Profile: EU_AIObservation
Parent: Observation
Id: eu-ai-observation
Title: "EU AI Generated Observation"
Description: "An Observation profile representing a clinical output generated by an AI system, including AI-related transparency metadata and links to the relevant patient, encounter, and AI system."

// =======================================================
// 1. STATUS & BASICS
// =======================================================
* status
* status ^short = "Workflow state: preliminary (unseen) | final (checked) | entered-in-error (overridden)"
* code 1..1 MS
* subject 1..1 MS

// SYS-10.1
* effective[x] 1..1 MS
* effective[x] only dateTime
* effectiveDateTime ^short = "Time the AI generated this result"

// =======================================================
// 2. DEVICE LINK (SYS-01 Context)
// =======================================================
* device 1..1 MS
* device only Reference(EU_AIDevice)
* device ^short = "Link to the AI Device that generated this result"

// =======================================================
// 3. AI-GENERATED FLAG (AI origin transparency)
// =======================================================
* interpretation
* interpretation ^slicing.discriminator.type = #value
* interpretation ^slicing.discriminator.path = "coding"
* interpretation ^slicing.rules = #open
* interpretation contains aiGeneratedFlag 1..1 MS
* interpretation[aiGeneratedFlag].coding = EUAIActCodeSystem#ai-generated
* interpretation[aiGeneratedFlag] ^short = "Mandatory flag indicating AI origin"


// =======================================================
// 5. EXTENSIONS (USE-04 & Law-02)
// =======================================================
* extension contains
    CaseSpecificIndication named caseIndication 1..1 MS and
    AutomatedDecisionFlag named automatedDecision 1..1 MS