Profile: EU_AIObservation
Parent: Observation
Id: eu-ai-observation
Title: "EU AI Generated Observation"
Description: "An Observation profile representing a clinical output generated by an AI system, including AI-related transparency metadata and links to the relevant patient, encounter, and AI system."

// =======================================================
//  STATUS & BASICS
// =======================================================
* subject 1..1 MS

// SYS-10.1
* effective[x] 1..1 MS
* effective[x] only dateTime
* effectiveDateTime ^short = "Time the AI generated this result"

// =======================================================
//  DEVICE LINK (SYS-01 Context)
// =======================================================
* device 1..1 MS
* device only Reference(EU_AIDevice)
* device ^short = "Link to the AI Device that generated this result"

// =======================================================
//  AI-GENERATED FLAG (AI origin transparency)
// =======================================================
* interpretation
* interpretation ^slicing.discriminator.type = #value
* interpretation ^slicing.discriminator.path = "coding"
* interpretation ^slicing.rules = #open
* interpretation contains aiGeneratedFlag 1..1 MS
* interpretation[aiGeneratedFlag].coding = EUAIInvolvementCodeSystem#ai-generated
* interpretation[aiGeneratedFlag] ^short = "Mandatory flag indicating AI origin"

// =======================================================
// EXTENSIONS (USE-04 & Law-02)
// =======================================================
* extension contains
    CaseSpecificIndication named caseIndication 1..1 MS and
    AutomatedDecisionFlag named automatedDecision 1..1 MS

* extension[caseIndication] ^short = "Clinical reason for AI use"
* extension[automatedDecision] ^short = "Automated decision flag"