Profile: EU_AIObservation
Parent: Observation
Id: eu-ai-observation
Title: "EU AI Act Observation (Validated Result)"
Description: "Profile for clinical findings generated by an AI system, implementing LAW-02 (AI Flag) and linking to the AI Device."

// =======================================================
// 1. STATUS & BASICS
// =======================================================
* status MS
* status ^short = "Workflow state: preliminary (unseen) | final (checked) | entered-in-error (overridden)"
* code 1..1 MS
* subject 1..1 MS

// SYS-10.1
* effective[x] 1..1 MS
* effective[x] only dateTime
* effectiveDateTime ^short = "Time the AI generated this result"

// =======================================================
// 2. DEVICE LINK (SYS-01 Context)
// =======================================================
* device 1..1 MS
* device only Reference(EU_AIDevice)
* device ^short = "Link to the AI Device that generated this result"

// =======================================================
// 3. AI-GENERATED FLAG (LAW-02)
// =======================================================
* interpretation MS
* interpretation ^slicing.discriminator.type = #value
* interpretation ^slicing.discriminator.path = "coding"
* interpretation ^slicing.rules = #open
* interpretation contains aiGeneratedFlag 1..1 MS
* interpretation[aiGeneratedFlag].coding = EUAIActCodeSystem#ai-generated
* interpretation[aiGeneratedFlag] ^short = "Mandatory flag indicating AI origin"


// =======================================================
// 5. EXTENSIONS (USE-04 & LAW-05)
// =======================================================
* extension contains
    CaseSpecificIndication named caseIndication 1..* MS 