// =======================================================
// 1. CODESYSTEM (Zentrale Terminologie)
// =======================================================

CodeSystem: EUAIActCodeSystem
Id: EUAIActCodeSystem
Title: "EU AI Act Custom Codes"
Description: "Central repository of legal and technical terms according to the EU AI Act."
* ^status = #active
* ^experimental = true 
* ^caseSensitive = true

// Core categories (SYS-01, SYS-05)
* #ai-system "AI System"
* #high-risk-ai "High-Risk AI System"
* #gpai "General Purpose AI"
* #model-card "AI Model Card"
* #ai-generated "AI Generated Result"

// Human-in-the-loop (HL-03.1)
* #human-override "Human Override"
* #human-validation "Human Validation"
* #human-correction "Human Correction"

// Transparency (LAW-07)
* #ai-transparency-info "AI Transparency Information"
* #informed-consent "Informed Consent"

// Performance Metrics (QUAL-01)
* #accuracy "Accuracy"
* #sensitivity "Sensitivity"
* #specificity "Specificity"

// Case-Specific Indication (USE-04)
* #triage "Triage and Prioritization"
* #screening "Screening"
* #second-opinion "Second Opinion"
* #diagnostic-support "Diagnostic Support"
* #treatment-planning "Treatment Planning"
* #prognosis "Prognostic Prediction"


* #ce-mark "CE Mark" "Indicates if the device has a CE mark."
* #notified-body-id "Notified Body ID" "Identifier of the notified body."
* #expected-lifetime "Expected Lifetime" "The expected lifetime of the AI system."
* #medical-purpose "Medical Purpose" "The intended medical purpose."
* #target-population "Target Population" "The intended target population."

// EHDS Usage Categories (LAW-03.1)
* #primary-use "Primary Use" "Processing for direct patient care."
* #secondary-use "Secondary Use" "Processing for research, AI training, or policy making."


// EHDS Data Categories for Secondary Use (Art. 51 EHDS-VO 2025/327)
* #ehr "Electronic Health Records (EHRs)" "Electronic health data from electronic health records (Art. 51 1a)"
* #health-factors "Health Determinants" "Data impacting on health, including socioeconomic, environmental and behavioural determinants (Art. 51 1b)"
* #healthcare-resources "Aggregated Healthcare Data" "Aggregated data on healthcare needs, resources, access, and financing (Art. 51 1c)"
* #pathogen-data "Pathogen Data" "Data on pathogens impacting on human health (Art. 51 1d)"
* #admin-claims "Administrative and Claims Data" "Health-related administrative data, including claims and reimbursement data (Art. 51 1e)"
* #human-genomic "Human Genomic Data" "Human genetic, epigenomic and genomic data (Art. 51 1f)"
* #molecular-omics "Molecular Omic Data" "Other human molecular data, such as proteomic, transcriptomic, metabolomic, lipidomic and other omic data (Art. 51 1g)"
* #device-generated-personal "Device-Generated Personal Data" "Person-generated electronic health data automatically generated by medical devices (Art. 51 1h)"
* #wellness-apps "Wellness Application Data" "Data from wellness applications (Art. 51 1i)"
* #professional-status "Healthcare Professional Data" "Data on the professional status, specialization, and institution of healthcare professionals (Art. 51 1j)"
* #public-health-registry "Public Health Registries" "Data from population-wide health data registries (Art. 51 1k)"
* #medical-mortality-registry "Medical and Mortality Registries" "Data from medical registries and mortality registries (Art. 51 1l)"
* #clinical-trial "Clinical Trial Data" "Data from clinical trials, clinical studies, and performance studies (Art. 51 1m)"
* #medical-device-other "Other Medical Device Data" "Other health data from medical devices (Art. 51 1n)"
* #medicinal-device-registry "Medicinal and Device Registries" "Data from registries for medicinal products and medical devices (Art. 51 1o)"
* #research-cohort-survey "Research Cohorts and Surveys" "Data from research cohorts, questionnaires, and health-related surveys (Art. 51 1p)"
* #biobank "Biobank Data" "Health data from biobanks and associated databases (Art. 51 1q)"

// AI Training Data Quality (Art. 10 AI Act)
* #representative "Representative" "Data is sufficiently representative of the target population."
* #error-free "Error-free" "Data is free of errors to the best extent possible."
* #complete "Complete" "Data is complete regarding the intended purpose."


//law 1
* #gdpr-art-6-1-a "Consent (Art. 6(1)(a))"
* #gdpr-art-6-1-b "Contract (Art. 6(1)(b))"
* #gdpr-art-6-1-d "Vital Interests (Art. 6(1)(d))"
* #gdpr-art-9-2-a "Explicit Consent (Art. 9(2)(a))"
* #gdpr-art-9-2-h "Health or Social Care (Art. 9(2)(h))"
* #gdpr-art-9-2-i "Public Health (Art. 9(2)(i))"
* #gdpr-art-9-2-j "Research (Art. 9(2)(j))"


// =======================================================
// 2. VALUESETS (Aktiv verwendete Filter)
// =======================================================

ValueSet: EUCaseSpecificIndicationVS
Id: eu-case-specific-indication-vs
Title: "EU AI Case-Specific Indication ValueSet"
Description: "Clinical and administrative reasons for AI application."
* ^status = #active
* ^experimental = true
* EUAIActCodeSystem#triage
* EUAIActCodeSystem#screening
* EUAIActCodeSystem#second-opinion
* EUAIActCodeSystem#diagnostic-support
* EUAIActCodeSystem#treatment-planning
* EUAIActCodeSystem#prognosis

ValueSet: EU_AI_PerformanceMetricVS
Id: eu-ai-performance-metric-vs
Title: "AI Performance Metric ValueSet"
Description: "Codes for technical quality and performance metrics."
* ^status = #active
* ^experimental = true
* EUAIActCodeSystem#accuracy
* EUAIActCodeSystem#sensitivity
* EUAIActCodeSystem#specificity


ValueSet: EHDS_UsageCategoryVS
Id: ehds-usage-category-vs
Title: "EHDS Usage Category ValueSet"
Description: "Defines whether the data usage is primary care or secondary use."
* ^status = #active
* ^experimental = true
* EUAIActCodeSystem#primary-use
* EUAIActCodeSystem#secondary-use


ValueSet: EHDS_DataCategoryVS
Id: ehds-data-category-vs
Title: "EHDS Data Category ValueSet (Final Regulation 2025/327)"
Description: "Mandatory categories of electronic health data for secondary use according to Art. 51 EHDS."
* ^status = #active
* ^experimental = true
* EUAIActCodeSystem#ehr
* EUAIActCodeSystem#health-factors
* EUAIActCodeSystem#healthcare-resources
* EUAIActCodeSystem#pathogen-data
* EUAIActCodeSystem#admin-claims
* EUAIActCodeSystem#human-genomic
* EUAIActCodeSystem#molecular-omics
* EUAIActCodeSystem#device-generated-personal
* EUAIActCodeSystem#wellness-apps
* EUAIActCodeSystem#professional-status
* EUAIActCodeSystem#public-health-registry
* EUAIActCodeSystem#medical-mortality-registry
* EUAIActCodeSystem#clinical-trial
* EUAIActCodeSystem#medical-device-other
* EUAIActCodeSystem#medicinal-device-registry
* EUAIActCodeSystem#research-cohort-survey
* EUAIActCodeSystem#biobank


ValueSet: EU_AI_DataQualityVS
Id: eu-ai-data-quality-vs
Title: "AI Data Quality ValueSet"
Description: "Attributes describing the quality of training data."
* ^status = #active
* ^experimental = true
* EUAIActCodeSystem#representative
* EUAIActCodeSystem#error-free
* EUAIActCodeSystem#complete

// =======================================================
// HUMAN INTERVENTION VALUESET (Für HL-03.1)
// =======================================================
ValueSet: EU_AI_Intervention_ValueSet
Id: eu-ai-intervention-vs
Title: "Human Intervention Type ValueSet"
Description: "Codes representing the type of human oversight or intervention."
* ^status = #active
* ^experimental = false
* EUAIActCodeSystem#human-override
* EUAIActCodeSystem#human-validation
* EUAIActCodeSystem#human-correction

// =======================================================
// CODESYSTEME 
// =======================================================
CodeSystem: GDPRArt6CodeSystem
Id: gdpr-art6-codesystem
Title: "GDPR Art 6 Legal Basis"
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* #gdpr-art-6-1-a "Consent (Art. 6(1)(a))"
* #gdpr-art-6-1-b "Contract (Art. 6(1)(b))"
* #gdpr-art-6-1-d "Vital Interests (Art. 6(1)(d))"

CodeSystem: GDPRArt9CodeSystem
Id: gdpr-art9-codesystem
Title: "GDPR Art 9 Exceptions"
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* #gdpr-art-9-2-a "Explicit Consent (Art. 9(2)(a))"
* #gdpr-art-9-2-h "Health or Social Care (Art. 9(2)(h))"
* #gdpr-art-9-2-i "Public Health (Art. 9(2)(i))"
* #gdpr-art-9-2-j "Research (Art. 9(2)(j))"

// =======================================================
// VALUESETS
// =======================================================
ValueSet: GDPR_Art6_LegalBasisVS
Id: gdpr-art6-legal-basis-vs
Title: "GDPR Art 6 Legal Basis for AI"
* ^experimental = false
* include codes from system GDPRArt6CodeSystem

ValueSet: GDPR_Art9_ExceptionVS
Id: gdpr-art9-exception-vs
Title: "GDPR Art 9 Exception for AI Health Data"
* ^experimental = false
* include codes from system GDPRArt9CodeSystem