// ============================================================================
// AI INVOLVEMENT
// Used in: Resource.meta.security to indicate how AI contributed to a resource.
// ValueSet use: binding for profiles that allow one or more AI-involvement labels.
// ============================================================================

CodeSystem: EUAIInvolvementCodeSystem
Id: eu-ai-involvement-cs
Title: "EU AI Involvement Code System"
Description: "Codes indicating the manner in which an AI system contributed to the content represented by a FHIR resource."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #ai-generated "AI Generated"
    "The substantive content of the resource was generated by an AI system."

* #ai-assisted "AI Assisted"
    "An AI system supported a human author, while the human remained responsible for creating the substantive content."

* #ai-reported "AI Reported"
    "An AI system transformed or reported existing information without independently asserting its clinical validity."

* #ai-asserted "AI Asserted"
    "An AI system asserted clinical or factual content as an output of its processing."

ValueSet: EUAIInvolvementVS
Id: eu-ai-involvement-vs
Title: "EU AI Involvement Value Set"
Description: "Codes used to classify how an AI system contributed to the content of a FHIR resource."

* ^status = #active
* ^experimental = false
* include codes from system EUAIInvolvementCodeSystem


// ============================================================================
// HUMAN OVERSIGHT
// Used in: EU_AIHumanOversightAssessment (ArtifactAssessment), typically in
// ArtifactAssessment.content.classifier or another coded oversight-action field.
// ValueSet use: required binding where the reviewer selects an oversight action.
// ============================================================================

CodeSystem: EUAIHumanOversightCodeSystem
Id: eu-ai-human-oversight-cs
Title: "EU AI Human Oversight Code System"
Description: "Codes describing actions taken by a human reviewer in response to an AI-generated output or recommendation."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #human-validation "Human Validation"
    "A human reviewer assessed the AI output and accepted it without changing its substantive content."

* #human-override "Human Override"
    "A human reviewer rejected the AI output or recommendation."

* #human-correction "Human Correction"
    "A human reviewer corrected erroneous or incomplete AI-generated content while retaining the corrected result as the documented outcome."

ValueSet: EUAIHumanOversightActionVS
Id: eu-ai-human-oversight-action-vs
Title: "EU AI Human Oversight Action Value Set"
Description: "Human oversight actions that may be documented in relation to an AI-generated output or recommendation."

* ^status = #active
* ^experimental = false
* include codes from system EUAIHumanOversightCodeSystem


// ============================================================================
// AI PERFORMANCE METRICS
// Used in: AIPerformanceMetrics extension within EU_AIModelCard.
// ValueSet use: binding for the coded metric type; the metric value is recorded
// separately, for example as Quantity, decimal, or another suitable datatype.
// ============================================================================

CodeSystem: EUAIPerformanceMetricCodeSystem
Id: eu-ai-performance-metric-cs
Title: "EU AI Performance Metric Code System"
Description: "Codes identifying performance characteristics used to document the evaluation of an AI system."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #accuracy "Accuracy"
    "The proportion of evaluated cases for which the AI system produced the correct result."

* #sensitivity "Sensitivity"
    "The proportion of relevant positive cases correctly identified by the AI system."

* #specificity "Specificity"
    "The proportion of relevant negative cases correctly identified by the AI system."

* #robustness "Robustness"
    "The ability of the AI system to maintain appropriate performance under variations, disturbances, or reasonably foreseeable conditions of use."

ValueSet: EUAIPerformanceMetricVS
Id: eu-ai-performance-metric-vs
Title: "EU AI Performance Metric Value Set"
Description: "Performance characteristics that may be documented for an AI system."

* ^status = #active
* ^experimental = false
* include codes from system EUAIPerformanceMetricCodeSystem


// ============================================================================
// CLINICAL VALIDATION STATUS
// Used in: AIClinicalValidationStatus extension within EU_AIModelCard.
// ValueSet use: required binding for the documented validation status.
// ============================================================================

CodeSystem: EUAIClinicalValidationStatusCodeSystem
Id: eu-ai-clinical-validation-status-cs
Title: "EU AI Clinical Validation Status Code System"
Description: "Codes indicating the documented clinical validation status of an AI system for its intended clinical use."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #clinically-validated "Clinically Validated"
    "Clinical validation for the documented intended use has been completed."

* #not-clinically-validated "Not Clinically Validated"
    "Clinical validation for the documented intended use has not been completed."

* #validation-in-progress "Validation In Progress"
    "Clinical validation is ongoing and no final validation conclusion has yet been documented."

* #technical-validation-only "Technical Validation Only"
    "Technical verification or validation has been performed, but clinical validation for the intended use has not been completed."

ValueSet: EUAIClinicalValidationStatusVS
Id: eu-ai-clinical-validation-status-vs
Title: "EU AI Clinical Validation Status Value Set"
Description: "Clinical validation statuses applicable to an AI system and its documented intended use."

* ^status = #active
* ^experimental = false
* include codes from system EUAIClinicalValidationStatusCodeSystem


// ============================================================================
// CASE-SPECIFIC INDICATION
// Used in: CaseSpecificIndication extension on EU_AIObservation.
// ValueSet use: binding for the clinical reason why the AI system was applied
// in the individual care context.
// ============================================================================

CodeSystem: EUAICaseSpecificIndicationCodeSystem
Id: eu-ai-case-specific-indication-cs
Title: "EU AI Case-Specific Indication Code System"
Description: "Codes describing the clinical purpose for which an AI system was applied in an individual case."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #triage "Triage and Prioritization"
    "Use of the AI system to support urgency assessment, prioritization, or routing."

* #screening "Screening"
    "Use of the AI system to identify individuals or findings that may require further assessment."

* #second-opinion "Second Opinion"
    "Use of the AI system to provide an additional assessment alongside a human clinical assessment."

* #diagnostic-support "Diagnostic Support"
    "Use of the AI system to support the identification or assessment of a diagnosis."

* #treatment-planning "Treatment Planning"
    "Use of the AI system to support selection, planning, or adaptation of treatment."

* #prognosis "Prognostic Prediction"
    "Use of the AI system to estimate a future clinical outcome, risk, or disease course."

ValueSet: EUAICaseSpecificIndicationVS
Id: eu-ai-case-specific-indication-vs
Title: "EU AI Case-Specific Indication Value Set"
Description: "Clinical purposes for applying an AI system in an individual care context."

* ^status = #active
* ^experimental = false
* include codes from system EUAICaseSpecificIndicationCodeSystem


// ============================================================================
// DATA QUALITY CHARACTERISTICS
// Used in: AITrainingData extension within EU_AIModelCard.
// ValueSet use: binding for documented quality characteristics of training,
// validation, or test data. These codes express an assessment, not an absolute
// guarantee that the data are entirely error-free or complete.
// ============================================================================

CodeSystem: EUAIDataQualityCodeSystem
Id: eu-ai-data-quality-cs
Title: "EU AI Data Quality Code System"
Description: "Codes describing assessed data-quality characteristics relevant to the development, validation, testing, or evaluation of an AI system."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #representative "Representative"
    "The data are assessed as sufficiently representative of the relevant population, setting, or intended use."

* #error-free "Error-Controlled"
    "The data were subject to measures intended to identify, reduce, and manage errors."

* #complete "Complete"
    "The data are assessed as sufficiently complete for the documented purpose."

* #relevant "Relevant"
    "The data are assessed as relevant to the documented purpose and intended use."

ValueSet: EUAIDataQualityVS
Id: eu-ai-data-quality-vs
Title: "EU AI Data Quality Value Set"
Description: "Assessed data-quality characteristics relevant to AI-system development, validation, testing, or evaluation."

* ^status = #active
* ^experimental = false
* include codes from system EUAIDataQualityCodeSystem


// ============================================================================
// ORGANIZATIONAL CONTACT PURPOSE
// Used in: EU_AIOrganization.contact slices, for example dpo and incident.
// No ValueSet is currently required because each contact slice fixes one code.
// ============================================================================

CodeSystem: EUAIContactPurposeCodeSystem
Id: eu-ai-contact-purpose-cs
Title: "EU AI Contact Purpose Code System"
Description: "Codes identifying organizational contact responsibilities relevant to data protection and AI-system governance."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #dpo "Data Protection Officer"
    "Contact point for the organization's data protection officer or data protection function."

* #ai-incident-reporting "AI Incident Reporting Contact"
    "Contact point designated to receive reports concerning AI-related incidents or serious incidents."


// ============================================================================
// EHDS USAGE CATEGORY
// Used in: EHDSUsageCategory extension on EU_AIProvenance.
// ValueSet use: required binding distinguishing primary from secondary use.
// ============================================================================

CodeSystem: EHDSUsageCategoryCodeSystem
Id: ehds-usage-category-cs
Title: "EHDS Usage Category Code System"
Description: "Codes distinguishing primary use from secondary use of electronic health data in the context of the European Health Data Space."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #primary-use "Primary Use"
    "Use of personal electronic health data for the provision of healthcare to the individual concerned."

* #secondary-use "Secondary Use"
    "Use of electronic health data for a permitted purpose other than the direct provision of healthcare to the individual concerned."

ValueSet: EHDSUsageCategoryVS
Id: ehds-usage-category-vs
Title: "EHDS Usage Category Value Set"
Description: "Categories distinguishing primary and secondary use of electronic health data in the EHDS context."

* ^status = #active
* ^experimental = false
* include codes from system EHDSUsageCategoryCodeSystem


// ============================================================================
// EHDS DATA CATEGORIES
// Used in: AITrainingData extension within EU_AIModelCard to describe categories
// of electronic health data used for training, validation, testing, or evaluation.
// ValueSet use: binding for one or more documented EHDS data categories.
// Note: These are implementation-guide codes aligned with Article 51 concepts;
// they are not intended as a verbatim reproduction of the Regulation.
// ============================================================================

CodeSystem: EHDSDataCategoryCodeSystem
Id: ehds-data-category-cs
Title: "EHDS Data Category Code System"
Description: "Codes representing categories of electronic health data that may be made available for secondary use under the EHDS."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #ehr "Electronic Health Records"
    "Electronic health data originating from electronic health records."

* #health-factors "Health Determinant Data"
    "Data concerning factors that influence health, including socioeconomic, environmental, and behavioural determinants."

* #healthcare-resources "Healthcare Needs, Resources and Financing Data"
    "Aggregated data concerning healthcare needs, allocated resources, access to healthcare, healthcare expenditure, and financing."

* #pathogen-data "Pathogen Data"
    "Data concerning pathogens that affect human health."

* #admin-claims "Administrative and Claims Data"
    "Health-related administrative data, including claims and reimbursement information."

* #human-genomic "Human Genetic, Epigenomic and Genomic Data"
    "Human genetic, epigenomic, and genomic data."

* #molecular-omics "Human Molecular Data"
    "Human molecular data, including proteomic, transcriptomic, metabolomic, lipidomic, and comparable omics data."

* #device-generated-personal "Person-Generated Device Data"
    "Personal electronic health data generated automatically through medical devices."

* #wellness-apps "Wellness Application Data"
    "Electronic health-related data generated through wellness applications."

* #professional-status "Healthcare Professional Data"
    "Data concerning the professional status, specialization, and institution of healthcare professionals involved in treatment."

* #public-health-registry "Population-Based Health Registry Data"
    "Data from population-based health registries."

* #medical-mortality-registry "Medical and Mortality Registry Data"
    "Data from medical registries and mortality registries."

* #clinical-trial "Clinical Study and Investigation Data"
    "Data from clinical trials, clinical studies, clinical investigations, and performance studies."

* #medical-device-other "Other Medical Device Data"
    "Other electronic health data generated through medical devices that are not represented by a more specific category."

* #medicinal-device-registry "Medicinal Product and Medical Device Registry Data"
    "Data from registries for medicinal products and medical devices."

* #research-cohort-survey "Research Cohort, Questionnaire and Survey Data"
    "Data from research cohorts, questionnaires, and health-related surveys."

* #biobank "Biobank Data"
    "Electronic health data from biobanks and associated databases."

ValueSet: EHDSDataCategoryVS
Id: ehds-data-category-vs
Title: "EHDS Data Category Value Set"
Description: "Categories of electronic health data that may be documented for secondary-use and AI-development contexts."

* ^status = #active
* ^experimental = false
* include codes from system EHDSDataCategoryCodeSystem


// ============================================================================
// EHDS SECONDARY-USE PURPOSE
// Used in: EHDSSecondaryUsePurpose extension on EU_AIProvenance and, where
// applicable, in AITrainingData within EU_AIModelCard.
// ValueSet use: binding for the permitted secondary-use purpose.
// Note: The codes summarize EHDS purpose categories for implementation use and
// do not replace the full legal conditions governing access and processing.
// ============================================================================

CodeSystem: EHDSSecondaryUsePurposeCodeSystem
Id: ehds-secondary-use-purpose-cs
Title: "EHDS Secondary-Use Purpose Code System"
Description: "Codes representing permitted categories of purpose for the secondary use of electronic health data under the EHDS."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #public-health "Public Health"
    "Activities in the area of public health, including protection against serious cross-border threats to health and public-health surveillance."

* #policy-regulatory "Policy-Making and Regulatory Activities"
    "Public-sector policy-making, planning, supervision, or regulatory activities in the health or care sectors."

* #statistics "Official Statistics"
    "Preparation and production of official statistics relating to health or care."

* #education-teaching "Education or Teaching"
    "Education or teaching activities in the health or care sectors."

* #scientific-research "Scientific Research"
    "Scientific research related to health or care that contributes to public health or health-technology development."

* #development-innovation "Development and Innovation"
    "Development and innovation activities for products, services, or processes contributing to public health, healthcare, or care."

* #algorithm-training-testing "Training, Testing and Evaluation of Algorithms"
    "Training, testing, and evaluation of algorithms, including algorithms used in medical devices, in-vitro diagnostic medical devices, AI systems, or digital health applications."

* #care-improvement "Improvement of Care Delivery"
    "Activities aimed at improving healthcare delivery, treatment, or the management of health systems."

ValueSet: EHDSSecondaryUsePurposeVS
Id: ehds-secondary-use-purpose-vs
Title: "EHDS Secondary-Use Purpose Value Set"
Description: "Purpose categories used to document the secondary use of electronic health data under the EHDS."

* ^status = #active
* ^experimental = false
* include codes from system EHDSSecondaryUsePurposeCodeSystem


// ============================================================================
// GDPR ARTICLE 6 LEGAL BASIS
// Used in: EU_AIProvenance.authorization[gdprArt6Basis].concept.
// ValueSet use: required binding for the documented Article 6 legal basis.
// This terminology records the asserted legal basis; it does not determine
// whether that basis is legally applicable in a specific processing context.
// ============================================================================

CodeSystem: GDPRArt6CodeSystem
Id: gdpr-art6-codesystem
Title: "GDPR Article 6 Legal Basis Code System"
Description: "Codes representing the legal bases listed in Article 6(1) GDPR for processing personal data."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #gdpr-art-6-1-a "Consent (Art. 6(1)(a))"
    "The data subject has given consent to the processing of personal data for one or more specific purposes."

* #gdpr-art-6-1-b "Contract (Art. 6(1)(b))"
    "Processing is necessary for the performance of a contract with the data subject or for pre-contractual measures requested by the data subject."

* #gdpr-art-6-1-c "Legal Obligation (Art. 6(1)(c))"
    "Processing is necessary for compliance with a legal obligation to which the controller is subject."

* #gdpr-art-6-1-d "Vital Interests (Art. 6(1)(d))"
    "Processing is necessary to protect the vital interests of the data subject or another natural person."

* #gdpr-art-6-1-e "Public Interest or Official Authority (Art. 6(1)(e))"
    "Processing is necessary for a task carried out in the public interest or in the exercise of official authority vested in the controller."

* #gdpr-art-6-1-f "Legitimate Interests (Art. 6(1)(f))"
    "Processing is necessary for legitimate interests pursued by the controller or a third party, subject to the conditions and limitations of Article 6(1)(f) GDPR."

ValueSet: GDPRArt6LegalBasisVS
Id: gdpr-art6-legal-basis-vs
Title: "GDPR Article 6 Legal Basis Value Set"
Description: "Legal bases listed in Article 6(1) GDPR for documenting the asserted lawful basis for processing personal data."

* ^status = #active
* ^experimental = false
* include codes from system GDPRArt6CodeSystem


// ============================================================================
// GDPR ARTICLE 9 CONDITION
// Used in: EU_AIProvenance.authorization[gdprArt9Condition].concept.
// ValueSet use: required binding for the documented Article 9(2) condition when
// special categories of personal data, such as health data, are processed.
// This IG includes the conditions most relevant to its healthcare use cases,
// not every condition contained in Article 9(2) GDPR.
// ============================================================================

CodeSystem: GDPRArt9CodeSystem
Id: gdpr-art9-codesystem
Title: "GDPR Article 9 Condition Code System"
Description: "Codes representing selected conditions in Article 9(2) GDPR under which special categories of personal data may be processed."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #gdpr-art-9-2-a "Explicit Consent (Art. 9(2)(a))"
    "The data subject has given explicit consent to the processing for one or more specified purposes, subject to applicable legal limitations."

* #gdpr-art-9-2-c "Vital Interests (Art. 9(2)(c))"
    "Processing is necessary to protect vital interests where the data subject is physically or legally incapable of giving consent."

* #gdpr-art-9-2-g "Substantial Public Interest (Art. 9(2)(g))"
    "Processing is necessary for reasons of substantial public interest on the basis of Union or Member State law and subject to appropriate safeguards."

* #gdpr-art-9-2-h "Health or Social Care (Art. 9(2)(h))"
    "Processing is necessary for preventive or occupational medicine, medical diagnosis, provision or management of health or social care, or related systems and services, subject to the applicable legal conditions."

* #gdpr-art-9-2-i "Public Health (Art. 9(2)(i))"
    "Processing is necessary for reasons of public interest in the area of public health on the basis of Union or Member State law and subject to appropriate safeguards."

* #gdpr-art-9-2-j "Research and Statistics (Art. 9(2)(j))"
    "Processing is necessary for archiving in the public interest, scientific or historical research, or statistical purposes, subject to Article 89(1) GDPR and an applicable legal basis."

ValueSet: GDPRArt9ConditionVS
Id: gdpr-art9-condition-vs
Title: "GDPR Article 9 Condition Value Set"
Description: "Selected Article 9(2) GDPR conditions relevant to processing health data and other special categories of personal data in this implementation guide."

* ^status = #active
* ^experimental = false
* include codes from system GDPRArt9CodeSystem


// ============================================================================
// AI DOCUMENTATION ARTIFACT TYPE
// Used in: EU_AIModelCard.type (DocumentReference.type).
// No ValueSet is currently required because the profile fixes type to #model-card.
// ============================================================================

CodeSystem: EUAIArtifactTypeCodeSystem
Id: eu-ai-artifact-type-cs
Title: "EU AI Artifact Type Code System"
Description: "Codes identifying AI-related documentation artifacts represented by this implementation guide."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #model-card "AI Model Card"
    "Documentation describing an AI system or model, including its intended use, limitations, performance, validation, data, and governance information."


// ============================================================================
// AI IDENTIFIER TYPE
// Used in: EU_AIDevice.identifier[euDatabaseId].type.
// No ValueSet is currently required because the identifier slice fixes the code.
// ============================================================================

CodeSystem: EUAIIdentifierTypeCodeSystem
Id: eu-ai-identifier-type-cs
Title: "EU AI Identifier Type Code System"
Description: "Codes identifying regulatory identifier types associated with an AI system."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #eu-ai-registration-number "EU AI Registration Number"
    "Registration number assigned to an AI system in the EU database established under the EU AI Act, where such registration is applicable."


// ============================================================================
// AI SYSTEM PROPERTY TYPE
// Used in: EU_AIDevice.property slices ceMark, notifiedBody,
// expectedLifetime, intendedPurpose, and targetPopulation.
// No ValueSet is currently required because each property slice fixes one code.
// These codes identify the meaning of Device.property; they are not identifiers.
// ============================================================================

CodeSystem: EUAISystemPropertyCodeSystem
Id: eu-ai-system-property-cs
Title: "EU AI System Property Code System"
Description: "Codes identifying structured properties used to describe regulatory and operational characteristics of an AI system in Device.property."

* ^status = #active
* ^experimental = false
* ^caseSensitive = true

* #ce-mark "CE Marking Status"
    "Indicates whether the AI system or relevant regulated product is documented as bearing a CE marking."

* #notified-body-id "Notified Body Identifier"
    "Identifies the notified body involved in the applicable conformity-assessment procedure, where relevant."

* #expected-lifetime "Expected Lifetime"
    "Identifies the expected operational lifetime of the AI system or software component."

* #intended-purpose "Intended Purpose"
    "Identifies the purpose for which the AI system is intended to be used according to the provider's documentation."

* #target-population "Target Population"
    "Identifies the population for which the AI system is intended or validated to be used."

// ============================================================================
// AI AUDIT ENTITY ROLE
// Used in: EU_AIAuditEvent.entity slices referenceDb and outputData.
// The codes are fixed on the respective slices and serve as the slicing
// discriminator for AuditEvent.entity.role.
// The ValueSet contains all entity roles defined for AI execution audit events.
// ============================================================================
CodeSystem: EUAIAuditEntityRoleCodeSystem
Id: eu-ai-audit-entity-role
Title: "EU AI Audit Entity Role Code System"
Description: "Roles used to distinguish entities involved in an AI execution audit event."
* ^caseSensitive = true
* ^content = #complete

* #reference-database "Reference Database"
    "An external database or knowledge source used during AI execution."

* #ai-output "AI Output"
    "A FHIR resource generated as output of the audited AI execution."

ValueSet: EUAIAuditEntityRoleValueSet
Id: eu-ai-audit-entity-role-vs
Title: "EU AI Audit Entity Role Value Set"
Description: "Roles of entities involved in an AI execution audit event."

* include codes from system EUAIAuditEntityRoleCodeSystem